// Fill out your copyright notice in the Description page of Project Settings.


#include "Main/ProjectGWGameInstance.h"

UProjectGWGameInstance::UProjectGWGameInstance()
{	
	// 생성자는 비워두고 Init()에서 초기화 작업을 진행
}

void UProjectGWGameInstance::Init()
{
	// 위쪽 생성자는 비워두고 여기에서 초기화
	// 각종 매니저 초기화
	// 각종 이벤트 등록? ㄴㄴ 이벤트는 매니저 안에 있
	Super::Init();
	UE_LOG(LogTemp, Warning, TEXT("Generated by PROJECT_GW_INSTANCE"));
	CharacterManager = NewObject<UCharacterManager>(this, UCharacterManager::StaticClass());
	CharacterManager->Init(); // 캐릭터 매니저 초기화
}

void UProjectGWGameInstance::Shutdown()
{
	CharacterManager->Shutdown(); // 캐릭터 매니저 종료
	Super::Shutdown();
}

//레벨간 이동, 외부로 나가는 매니저를 생성후 여기에 부름

//매니저 GEt 메소드 만들기

// 이벤트를 만들면 기본적으로 구독이 돼어있나?
// 매니저의 생성자에 만들면 되는건지, 매니저를 통해 Game Instace에서 구독을 해야하는건지
// 확인이 필요 아마 후자일 것으로 확인됌(후자일 경우 생성된 이벤트를 한번에 구독시키는 매소드 생성 필요)

